export const unmeaningfulPhrases = [
  'na',
  'no',
  'no need',
  'no needed',
  'no need support',
  'no needed support',
  'nothing i need',
  'none',
  'non',
  'no support',
  'no support needed',
  'no support required',
  'nothing',
  'i dont need support',
  'i dont need it',
  'i dont need',
  'i dont need any',
  'i dont need any support',
  'nothing do i need',
  'nothing i do need',
  'i don need support',
  'i don need it',
  'i don need',
  'i don need any',
  'i don need any support',
  'thank you',
  'its fine',
  'im fine',
  'all good',
  'all good thanks',
  'none required',
  'no required',
  'nothing required',
  'im ok',
  'im good',
  'im ok thanks',
  'thanks',
  'no thanks',
  'sorry',
  'clicked by mistake',
  'selected by mistake',
  'clicked by accident',
  'selected by accident',
  'pressed it accidentally',
  'clicked this by mistake',
  'selected this by mistake',
  'clicked this by accident',
  'selected this by accident',
  'clicked by mistake sorry',
  'selected by mistake sorry',
  'clicked by accident sorry',
  'selected by accident sorry',
  'pressed it accidentally sorry',
  'clicked this by mistake sorry',
  'selected this by mistake sorry',
  'clicked this by accident sorry',
  'selected this by accident sorry',
];
